version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.database:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
    ports:
      - 27017:27017
    command: ['-f', '/etc/mongod.conf']
    # restart: unless-stopped
